# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- name: MAVEN_OPTS
  value: '-Xms1024m -Xmx4096m -client -XX:MaxPermSize=500m  -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xverify:none'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean deploy'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      'env | sort'

- task: ArtifactoryMaven@2
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    artifactoryResolverService: 'testazure-sun-connection'
    targetResolveReleaseRepo: 'sun-mvn-opts-libs-release'
    targetResolveSnapshotRepo: 'sun-mvn-opts-libs-snapshot'
    artifactoryDeployService: 'testazure-sun-connection'
    targetDeployReleaseRepo: 'sun-mvn-opts-libs-release-local'
    targetDeploySnapshotRepo: 'sun-mvn-opts-libs-snapshot-local'
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'testazure-sun-connection'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'